[versions]
kotlin = "1.5.21"
ktor = "1.6.1"
adventure = "4.10.0"

[plugins]
indra-git = { id = "net.kyori.indra.git", version = "2.0.6" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin"}
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "10.2.0" }

[libraries]
adventure-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventure" }
cache4k = { group = "io.github.reactivecircus.cache4k", name = "cache4k", version = "0.4.0" }
kotlinx-html = { group = "org.jetbrains.kotlinx", name = "kotlinx-html", version = "0.7.3" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.2.2" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-websockets = { group = "io.ktor", name = "ktor-websockets", version.ref = "ktor" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.2.3" }

[bundles]
ktor-server = [ "ktor-server-core", "ktor-server-netty", "ktor-websockets" ]
