name: "build"

on: ["pull_request", "push", "workflow_dispatch"]

concurrency:
  group: ${{ github.ref }}-build
  cancel-in-progress: true

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "setup jdk 11"
        uses: "actions/setup-java@v2"
        with:
          distribution: "adopt"
          java-version: "11"
      - name: "build"
        run: "./gradlew build"
      - name: "setup ssh"
        uses: webfactory/ssh-agent@v0.5.2
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          ssh-private-key: ${{ secrets.DOCKER_HOST_SSH_KEY }}
      - name: "login to ghcr"
        uses: docker/login-action@v1
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "deploy docker"
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
          echo ${{ secrets.DOCKER_HOST_SSH_SIG }} > ~/.ssh/known_hosts
          docker-compose build
          docker-compose push
          DOCKER_HOST="${{ secrets.DOCKER_HOST }}" docker stack deploy --with-registry-auth --compose-file=docker-compose.yml adventure-webui
