name: "build"

on:
  pull_request:
  push:
    branches-ignore: [ "main" ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "setup env"
        id: "setup"
        uses: "KyoriPowered/.github/.github/actions/setup-java-env@trunk"
        with:
          runtime_version: 21
          publishing_branch_regex: 'main'
          gradle_warning_mode: "all"
      - name: "build"
        run: "./gradlew build"
